'use strict';
const $=id=>document.getElementById(id),canvas=$('road'),ctx=canvas.getContext('2d');
const W=720,H=820,horizon=260,view=1050;
const themes={garden:{name:'花園彎道',sky:'#a8dfdf',top:'#64b9ce',grass:'#8dbd6e',grass2:'#7cac61',road:'#566c6e',edge:'#fff2ca',accent:'#ed8875',curve:.65},coast:{name:'夕陽海岸',sky:'#ffcb9d',top:'#f39583',grass:'#67b6b9',grass2:'#50a4af',road:'#5e6977',edge:'#ffe1bb',accent:'#efab72',curve:.95},night:{name:'霓虹夜市',sky:'#655584',top:'#28294e',grass:'#625675',grass2:'#514562',road:'#383c58',edge:'#c9b4fa',accent:'#f2a4c7',curve:1.18}};
let selected='garden',game=null,last=0,raf=0,toastUntil=0,audio=null,soundOn=false;
const keys={left:false,right:false,drift:false};
const clamp=(x,min,max)=>Math.max(min,Math.min(max,x));
function clearInputs(){keys.left=keys.right=keys.drift=false;for(const id of ['left','right','drift'])$(id).classList.remove('held');dragId=null;}
function show(id){for(const name of ['intro','race-screen','result'])$(name).hidden=name!==id;}
function notify(text){$('toast').textContent=text;toastUntil=game?game.elapsed+2.2:0;}
function beep(freq=600,duration=.12){if(!soundOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.7,audio.currentTime+duration);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function create(mode){const easy=mode==='cruise',lapLength=easy?1850:2300,laps=easy?2:3,total=lapLength*laps;const items=[];const spacing=easy?200:135;
 for(let z=380;z<total-120;z+=spacing){const lane=[-.67,0,.67][Math.floor(Math.random()*3)],roll=Math.random();const type=roll<.32?'star':roll<.48?'box':roll<.76?'banana':'cone';items.push({z:z+Math.random()*50,x:lane,type,hit:false});if(type==='star')items.push({z:z+65,x:lane,type:'star',hit:false});}
 return {mode,theme:selected,laps,lapLength,total,base:easy?103:148,distance:0,x:0,speed:0,elapsed:0,countdown:3,status:'countdown',drift:0,wasDrifting:false,boost:0,shield:0,slow:0,invuln:0,stars:0,boosts:0,hits:0,items,seed:Math.random()*8,rivals:[{name:'薄荷號',color:'#b8dfa3',x:-.55,distance:75,factor:easy?.96:1.00,finish:null,slow:0},{name:'莓果號',color:'#eda3be',x:.6,distance:45,factor:easy?.91:.96,finish:null,slow:0},{name:'藍莓號',color:'#a3cce7',x:0,distance:-15,factor:easy?.87:.92,finish:null,slow:0}]};
}
function start(mode){cancelAnimationFrame(raf);clearInputs();game=create(mode);toastUntil=0;$('pause-overlay').hidden=true;$('toast').textContent='';$('countdown').textContent='3';show('race-screen');window.scrollTo(0,0);canvas.focus({preventScroll:true});last=performance.now();draw();hud();raf=requestAnimationFrame(frame);}
function curve(z){const t=themes[game.theme];return (Math.sin(z/420+game.seed)*.72+Math.sin(z/970+game.seed)*.35)*t.curve;}
function releaseDrift(){if(!game)return;if(game.drift>=.28){const strength=game.drift;game.boost=Math.max(game.boost,1.15+strength*1.4);game.boosts++;notify(strength>=.8?'超級甩尾！衝出去！':'甩尾加速！');beep(950,.22);}game.drift=0;}
function collect(item){item.hit=true;if(item.type==='star'){game.stars++;notify('星星 +1！');beep(870,.1);}else if(item.type==='box'){if(Math.random()<.5){game.shield=7;notify('護盾到手！擋一次碰撞');beep(710,.16);}else{game.boost=Math.max(game.boost,2);game.boosts++;notify('道具加速！');beep(1100,.2);}}else if(game.invuln<=0){if(game.shield>0){game.shield=0;game.invuln=1;notify('護盾擋住了，繼續走！');}else{game.slow=1.45;game.invuln=1.7;game.speed*=.48;game.hits++;notify(item.type==='banana'?'哎呀香蕉！慢一下就好':'碰到路障！繼續開就好');beep(190,.2);}}}
function simulate(dt){if(!game||game.status==='paused'||game.status==='finished')return;if(game.status==='countdown'){game.countdown-=dt;$('countdown').textContent=game.countdown>0?String(Math.ceil(game.countdown)):'';if(game.countdown<=0){game.status='running';notify('GO！左右轉，放心開！');beep(1000,.25);}return;}
 const old=game.distance;game.elapsed+=dt;for(const name of ['boost','shield','slow','invuln'])game[name]=Math.max(0,game[name]-dt);
 const steering=(keys.right?1:0)-(keys.left?1:0);const drifting=keys.drift&&steering!==0;
 if(game.wasDrifting&&!keys.drift)releaseDrift();if(drifting)game.drift=Math.min(1,game.drift+dt*.48);else if(!keys.drift)game.drift=0;game.wasDrifting=keys.drift;
 const target=game.base*(game.boost>0?1.55:1)*(game.slow>0?.52:1)*(Math.abs(game.x)>1?.52:1);
 game.speed+=(target-game.speed)*Math.min(1,dt*3.5);game.x=clamp(game.x+steering*dt*(drifting?1.02:1.3)-curve(game.distance)*dt*.10,-1.38,1.38);game.distance+=game.speed*dt;
 for(const item of game.items)if(!item.hit&&item.z>=old-12&&item.z<=game.distance+12&&Math.abs(item.x-game.x)<.24)collect(item);
 game.rivals.forEach((r,i)=>{if(r.finish!==null)return;r.slow=Math.max(0,r.slow-dt);if(Math.floor(game.elapsed/7)!==Math.floor((game.elapsed-dt)/7)&&Math.random()<.4)r.slow=1.2;const speed=game.base*r.factor*(1+.035*Math.sin(game.elapsed*.7+i))*(r.slow>0?.62:1);r.distance+=speed*dt;r.x=clamp(r.x+Math.sin(game.elapsed*.85+i)*dt*.11,-.76,.76);if(r.distance>=game.total){r.distance=game.total;r.finish=game.elapsed;}});
 if(game.elapsed>toastUntil)$('toast').textContent='';const previousLap=Math.floor(old/game.lapLength),newLap=Math.floor(game.distance/game.lapLength);if(newLap>previousLap&&newLap<game.laps){notify(`第 ${newLap+1} 圈！${newLap===game.laps-1?'最後一圈，走！':''}`);beep(760,.2);}if(game.distance>=game.total)finish();
}
function position(){return 1+game.rivals.filter(r=>r.distance>game.distance||r.finish!==null).length;}
function hud(){if(!game)return;$('rank').textContent=`${position()} / 4`;$('lap').textContent=`${Math.min(game.laps,Math.floor(game.distance/game.lapLength)+1)} / ${game.laps}`;$('stars').textContent=game.stars;$('speed').textContent=Math.round(game.speed*.68);$('drift-fill').style.width=`${game.drift*100}%`;$('drift-label').textContent=game.boost>0?'加速中！':game.shield>0?'護盾保護中':'甩尾能量';}
function project(ahead,lane=0){const p=clamp(1-ahead/view,0,1),half=25+Math.pow(p,1.35)*W*.43;return {p,x:W/2+(curve(game.distance+ahead)-curve(game.distance))*Math.sin(p*Math.PI)*W*.18+lane*half,y:horizon+p*p*(H-horizon),half};}
function poly(points,fill){ctx.fillStyle=fill;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
function roundRect(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function star(x,y,size){ctx.fillStyle='#ffe16a';ctx.strokeStyle='#956d40';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<10;i++){const r=i%2?size*.44:size,a=-Math.PI/2+i*Math.PI/5;const xx=x+Math.cos(a)*r,yy=y+Math.sin(a)*r;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();ctx.fill();ctx.stroke();}
function kart(x,y,s,color,player=false){ctx.save();ctx.translate(x,y);if(player)ctx.rotate(((keys.right?1:0)-(keys.left?1:0))*(keys.drift?.11:.04));ctx.scale(s,s);ctx.fillStyle='#193b3d55';ctx.beginPath();ctx.ellipse(0,5,44,10,0,0,Math.PI*2);ctx.fill();if(player&&game.boost>0){poly([[-25,0],[-14,28],[-7,2]],'#ffb953');poly([[8,2],[18,30],[26,0]],'#ffcf65');}
 roundRect(-45,-36,18,43,7,'#22373b');roundRect(27,-36,18,43,7,'#22373b');roundRect(-29,-72,12,21,4,'#22373b');roundRect(17,-72,12,21,4,'#22373b');roundRect(-29,-66,58,68,12,color);roundRect(-23,-11,46,13,4,'#fff1ce');roundRect(-19,-54,38,22,7,'#21413b');ctx.fillStyle=player?'#e58f72':'#edd2ad';ctx.beginPath();ctx.arc(0,-64,15,0,Math.PI*2);ctx.fill();roundRect(-16,-82,32,18,8,player?'#f6ce6b':color);roundRect(-11,-72,22,7,3,'#204044');ctx.fillStyle='#24413b';ctx.beginPath();ctx.arc(0,-26,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffde85';ctx.beginPath();ctx.arc(-4,-29,1.8,0,Math.PI*2);ctx.arc(4,-29,1.8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffde85';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-27,6,.2,Math.PI-.2);ctx.stroke();
 if(player&&game.shield>0){ctx.strokeStyle='#a5ffff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,-35,55,67,0,0,Math.PI*2);ctx.stroke();}if(player&&keys.drift&&game.drift>.08){for(let i=0;i<4;i++){ctx.strokeStyle=game.drift>.8?'#ffcf65':'#baf9ee';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-40-i*3,1+i*4);ctx.lineTo(-50-i*5,8+i*6);ctx.moveTo(40+i*3,1+i*4);ctx.lineTo(50+i*5,8+i*6);ctx.stroke();}}
 ctx.restore();}
function object(item,p){const s=9+p.p*p.p*38,x=p.x,y=p.y;ctx.save();if(item.type==='star')star(x,y-s,s);else if(item.type==='box'){roundRect(x-s,y-s*2,s*2,s*2,5,'#6cc6d5');ctx.strokeStyle='#fff2ce';ctx.lineWidth=3;ctx.strokeRect(x-s,y-s*2,s*2,s*2);ctx.fillStyle='#fff4da';ctx.font=`900 ${s*1.5}px system-ui`;ctx.textAlign='center';ctx.fillText('?',x,y-s*.35);}else if(item.type==='cone'){poly([[x-s,y],[x,y-s*2.3],[x+s,y]],'#ff9b6b');poly([[x-s*.65,y-s*.6],[x-s*.25,y-s*1.65],[x+s*.25,y-s*1.65],[x+s*.65,y-s*.6]],'#fff0ce');roundRect(x-s*1.3,y-3,s*2.6,6,2,'#466264');}else{ctx.strokeStyle='#8d6c3e';ctx.lineWidth=s*.58;ctx.lineCap='round';ctx.beginPath();ctx.arc(x,y-s*1.3,s,.1,Math.PI*.9);ctx.stroke();ctx.strokeStyle='#ffdf62';ctx.lineWidth=s*.42;ctx.stroke();ctx.strokeStyle='#ffdf62';ctx.lineWidth=s*.3;ctx.beginPath();ctx.moveTo(x,y-s*.2);ctx.lineTo(x-s*.8,y-s*1.3);ctx.moveTo(x,y-s*.2);ctx.lineTo(x+s*.8,y-s*1.3);ctx.stroke();}ctx.restore();}
function scenery(t){const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,t.top);sky.addColorStop(1,t.sky);ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle=t.grass;ctx.fillRect(0,horizon,W,H-horizon);const sun=game.theme==='night'?'#e0d6fa':'#ffe4a3';ctx.fillStyle=sun;ctx.beginPath();ctx.arc(W*.79,90,38,0,Math.PI*2);ctx.fill();
 if(game.theme==='garden'){poly([[0,horizon],[80,185],[145,horizon],[230,193],[315,horizon],[420,194],[570,horizon],[690,198],[W,horizon]],'#72aa84');for(let i=0;i<3;i++){const x=115+i*40;roundRect(x,168-i%2*25,29,93+i%2*25,2,'#f3ddac');poly([[x-7,168-i%2*25],[x+14,137-i%2*25],[x+36,168-i%2*25]],'#dc8c92');roundRect(x+11,198-i%2*25,7,15,2,'#5c787d');}}else if(game.theme==='coast'){ctx.fillStyle='#55a4b2';ctx.fillRect(0,horizon-32,W,55);poly([[0,horizon-20],[110,210],[210,horizon-12],[W,horizon]],'#dfbd8a');roundRect(115,160,27,82,2,'#fff3d0');roundRect(115,190,27,16,1,'#ec9280');poly([[110,162],[128,140],[148,162]],'#655765');}else{for(let i=0;i<12;i++){const x=i*65,h=30+(i*47)%85;roundRect(x,horizon-h,55,h,2,i%2?'#4a4569':'#4d3c5e');for(let j=0;j<3;j++)roundRect(x+9+j*13,horizon-h+12,7,12,1,j%2?'#eaa6c5':'#a1dacc');}ctx.fillStyle='#f1d5ee';for(let i=0;i<20;i++)ctx.fillRect((i*143)%W,(i*57)%170,2,2);}}
function draw(){if(!game)return;const t=themes[game.theme];scenery(t);
 for(let i=0;i<100;i++){const far=(1-i/100)*view,near=(1-(i+1)/100)*view,a=project(far),b=project(near),band=Math.floor((game.distance+near)/60)%2;poly([[0,a.y],[W,a.y],[W,b.y],[0,b.y]],band?t.grass:t.grass2);poly([[a.x-a.half-12*a.p,a.y],[a.x+a.half+12*a.p,a.y],[b.x+b.half+12*b.p,b.y],[b.x-b.half-12*b.p,b.y]],band?t.edge:t.accent);poly([[a.x-a.half,a.y],[a.x+a.half,a.y],[b.x+b.half,b.y],[b.x-b.half,b.y]],t.road);
 if(Math.floor((game.distance+near)/90)%2===0)for(const lane of [-.33,.33])poly([[a.x+lane*a.half-2*a.p,a.y],[a.x+lane*a.half+2*a.p,a.y],[b.x+lane*b.half+2*b.p,b.y],[b.x+lane*b.half-2*b.p,b.y]],'#fff0c880');
 const at=(game.distance+near)%game.lapLength;if(at<25){poly([[a.x-a.half,a.y],[a.x+a.half,a.y],[b.x+b.half,b.y],[b.x-b.half,b.y]],'#f4f1d4');for(let j=0;j<10;j+=2)poly([[a.x-a.half+a.half*j/5,a.y],[a.x-a.half+a.half*(j+1)/5,a.y],[b.x-b.half+b.half*(j+1)/5,b.y],[b.x-b.half+b.half*j/5,b.y]],'#34454a');}}
 for(let i=0;i<10;i++){const z=(Math.floor(game.distance/150)+i+1)*150,d=z-game.distance;if(d>view)continue;const p=project(d),s=8+p.p*p.p*65;for(const sign of [-1,1]){const x=p.x+sign*(p.half+s*.7+20);if(game.theme==='night'){roundRect(x-s*.1,p.y-s*1.8,s*.2,s*1.8,1,'#403c58');roundRect(x-s*.5,p.y-s*2,s,s*.55,3,i%2?'#efa7c5':'#a3ddd3');}else{roundRect(x-s*.08,p.y-s*.6,s*.16,s*.6,1,'#876741');ctx.fillStyle=game.theme==='coast'?'#639c83':'#568a64';ctx.beginPath();ctx.arc(x,p.y-s,s*.57,0,Math.PI*2);ctx.fill();}}}
 const visible=game.items.filter(o=>!o.hit&&o.z-game.distance>0&&o.z-game.distance<view).map(o=>({ahead:o.z-game.distance,item:o}));for(const r of game.rivals){const ahead=r.distance-game.distance+25;if(ahead>0&&ahead<view)visible.push({ahead,rival:r});}visible.sort((a,b)=>b.ahead-a.ahead);for(const o of visible){const p=project(o.ahead,o.item?o.item.x:o.rival.x);if(o.item)object(o.item,p);else kart(p.x,p.y,.16+p.p*p.p*.9,o.rival.color);}
 const p=project(35,game.x);ctx.save();if(game.invuln>0&&Math.floor(game.elapsed*8)%2)ctx.globalAlpha=.55;kart(p.x,H-26,1.45,'#f6ce6b',true);ctx.restore();ctx.fillStyle='#ffffffa0';ctx.font='800 15px system-ui';ctx.textAlign='left';ctx.fillText(t.name,18,H-16);
}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;simulate(dt);if(game&&game.status!=='finished'){draw();hud();raf=requestAnimationFrame(frame);}}
function pause(){if(!game||!['running','countdown'].includes(game.status))return;game.beforePause=game.status;game.status='paused';game.drift=0;game.wasDrifting=false;clearInputs();$('pause-overlay').hidden=false;$('countdown').textContent='';}
function resume(){if(!game||game.status!=='paused')return;game.status=game.beforePause;clearInputs();$('pause-overlay').hidden=true;last=performance.now();}
function pick(){cancelAnimationFrame(raf);clearInputs();game=null;$('pause-overlay').hidden=true;show('intro');window.scrollTo(0,0);}
function formatTime(s){return `${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}.${Math.floor(s%1*10)}`;}
function finish(){game.distance=game.total;game.status='finished';clearInputs();const rank=position();$('finish-title').textContent=rank===1?'第一名！今天不慌張！':`第 ${rank} 名，平安完賽！`;$('finish-sub').textContent=`${themes[game.theme].name} · ${game.mode==='cruise'?'兜風':'正式賽'} · ${game.laps} 圈。${game.hits?`碰到 ${game.hits} 次障礙，也都開回來了。`:'一路順順，漂亮！'}`;$('time-result').textContent=formatTime(game.elapsed);$('star-result').textContent=game.stars;$('boost-result').textContent=game.boosts;const ranking=[{name:'你 / 多拉號',time:game.elapsed,you:true},...game.rivals.map(r=>({name:r.name,time:r.finish??game.elapsed+(game.total-r.distance)/(game.base*r.factor),you:false,finished:r.finish!==null}))].sort((a,b)=>a.time-b.time);$('podium').replaceChildren();ranking.forEach((r,i)=>{const p=document.createElement('p');if(r.you)p.className='you';const name=document.createElement('span'),time=document.createElement('span');name.textContent=`${i+1}. ${r.name}`;time.textContent=r.you||r.finished?formatTime(r.time):'還在賽道上';p.append(name,time);$('podium').append(p);});show('result');window.scrollTo(0,0);beep(rank===1?1200:780,.3);}
let dragId=null,dragX=0;
for(const id of ['left','right','drift']){const b=$(id);b.addEventListener('pointerdown',e=>{if(!game||!['running','countdown'].includes(game.status))return;e.preventDefault();b.setPointerCapture(e.pointerId);keys[id]=true;b.classList.add('held');});const release=e=>{e.preventDefault();keys[id]=false;b.classList.remove('held');};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',()=>{keys[id]=false;b.classList.remove('held');});b.addEventListener('contextmenu',e=>e.preventDefault());}
canvas.addEventListener('pointerdown',e=>{if(!game||game.status!=='running')return;e.preventDefault();dragId=e.pointerId;dragX=e.clientX;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==dragId||!game||game.status!=='running')return;const dx=e.clientX-dragX;dragX=e.clientX;game.x=clamp(game.x+dx/canvas.getBoundingClientRect().width*2.4,-1.38,1.38);});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{dragId=null;});
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLButtonElement&&e.code==='Space')return;const code=e.code;if(['ArrowLeft','ArrowRight','KeyA','KeyD','Space','ShiftLeft','ShiftRight','KeyP','Escape'].includes(code)&&game&&game.status!=='finished'){e.preventDefault();if(code==='KeyP'||code==='Escape'){if(!e.repeat)game.status==='paused'?resume():pause();return;}if(game.status==='paused')return;if(code==='ArrowLeft'||code==='KeyA')keys.left=true;if(code==='ArrowRight'||code==='KeyD')keys.right=true;if(code==='Space'||code.startsWith('Shift'))keys.drift=true;}});
window.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA'].includes(e.code))keys.left=false;if(['ArrowRight','KeyD'].includes(e.code))keys.right=false;if(e.code==='Space'||e.code.startsWith('Shift'))keys.drift=false;});window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
for(const button of document.querySelectorAll('[data-track]'))button.onclick=()=>{selected=button.dataset.track;for(const b of document.querySelectorAll('[data-track]')){b.classList.toggle('chosen',b===button);b.setAttribute('aria-pressed',String(b===button));}};
$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=`音效：${soundOn?'開':'關'}`;$('sound').setAttribute('aria-pressed',String(soundOn));if(soundOn)beep();};$('cruise').onclick=()=>start('cruise');$('race').onclick=()=>start('race');$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=pick;$('pick').onclick=pick;$('again').onclick=()=>start(game.mode);
